[Feat] 해시태그 관리 페이지
linkarchive/Front-End pull request #194
Opened 2023-07-16 17:06 UTC by dev-hamster

## 개요 :mag:

- https://github.com/linkarchive/Front-End/issues/181

## 작업사항 :memo:

 - 해시태그 추가 API 연동
-  자주 사용하는 태그 API 연동

`/queries` 디렉토리를 추가해 query 훅을 분리하였습니다

## 기타
자주 사용하는 태그 무한스크롤이 추가로 구현이 필요합니다(이슈에 TODO 추가하겠습니다!)

2023-07-16 17:09 UTC, dev-hamster commented on src/queries/index.ts
2회 이상 반복해서 사용하여 추출했습니다

2023-07-17 07:11 UTC, 1yoouoo requested changes
네 확인했습니다..!

근데 dev가 병합이 안되어있어가지고 병합 후에 pr 부탁드려도 될까요?

충돌났을 때 로컬에서 해결 후 병합하는 게 좋을 거 같아요

2023-07-19 07:13 UTC, dev-hamster commented
넵 알겠습니다

2023-07-20 07:03 UTC, 1yoouoo approved these changes

2023-07-21 11:24 UTC, 1yoouoo requested changes
ㅎㅎ

2023-07-21 11:24 UTC, 1yoouoo approved these changes

2023-07-21 11:24 UTC, merged