[Design] input component 디자인
linkarchive/Front-End pull request #39
Opened 2023-05-12 06:55 UTC by dev-hamster

## 개요 :mag:

링크 추가 페이지 디자인 작업입니다.

## 작업사항 :memo:

- #33 
- input 컴포넌트 디자인 작업
- 링크 추가 페이지 레이아웃 작업

2023-05-12 07:06 UTC, 1yoouoo commented on src/components/Create/LinkInfo.tsx
> +        <p className='desc'>
스타일드 컴포넌트와 className을 혼용해서 사용하는 이유가 있을까요?

2023-05-12 07:06 UTC, 1yoouoo commented on src/components/Input/index.tsx
> +const Wrapper = styled.div`
```suggestion
const Wrapper = styled.div<{props? : any}>`
```
이런식으로 스타일드 컴포넌트에 props를 전달해서 처리할 수 있을까요?

2023-05-13 02:24 UTC, dev-hamster commented on src/components/Create/LinkInfo.tsx
> +        <p className='desc'>
Wrapper > .thumb 이렇게 선택하는 방식을 선호해서요! 더 좋은 방법이 있나요?

2023-05-13 02:27 UTC, dev-hamster commented on src/components/Input/index.tsx
> +const Wrapper = styled.div`
넵 맞습니다! 다만 패딩이나 마진값 추가만을 위한 의도로 className을 추가했습니다. 유의미한 props를 정의하기 애매해서요

2023-05-13 03:29 UTC, 1yoouoo requested changes

2023-05-13 03:29 UTC, 1yoouoo commented on src/components/Create/LinkInfo.tsx
> +`;
```suggestion
    <Wrapper>
      <Thumb>
        <a href='/' target='_blank' rel='noreferrer noopener'>
          <Image src='/test.png' alt='' fill />
        </a>
      </Thumb>
      <Contents>
        <Desc>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint itaque magnam laborum,
          voluptatibus consequuntur ducimus doloribus est, aut laboriosam atque ipsam blanditiis nam
          vitae aspernatur reiciendis fugit iure, assumenda dolore.
        </Desc>
      </Contents>
    </Wrapper>
  );
};

export default LinkInfo;

const Wrapper = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
`;

const Thumb = styled.div`
  position: relative;
  width: 84px;
  height: 84px;
  margin-right: 8px;
`;

const Contents = styled.div`
  width: 223px;
  font-weight: 400;
  font-size: 12px;
  line-height: 14px;
`;

const Desc = styled.p`
  overflow: hidden;
  height: 33px;
  color: #a1a1a1;
  text-overflow: ellipsis;
`;
```

2023-05-13 03:29 UTC, 1yoouoo commented on src/components/Input/index.tsx
> +`;
```suggestion
    <Wrapper className={className}>
      <Label htmlFor={id}>제목</Label>
      <InputWrapper>
        <StyledInput
          type='text'
          name=''
          id={id}
          value={value}
          onChange={(e) => {
            setValue(e.target.value);
          }}
          color='red' // 예시
        />
        {children}
      </InputWrapper>
      <Error>에러메세지</Error>
    </Wrapper>
  );
};

Input.deafultProps = {
  className: '',
};

export default Input;
export { InputWithButton };

const Wrapper = styled.div``;

const Label = styled.label`
  display: block;
  margin-bottom: 7px;

  font-weight: 600;
  font-size: 18px;
  line-height: 21px;
  color: var(--font-color-darkGray);
`;

const InputWrapper = styled.div`
  display: flex;
  flex-direction: row;
  height: 35px;
`;

const StyledInput = styled.input`
  width: 100%;
  padding-left: 16px;
  border-radius: 4px;
  border: 1px solid;
  color: ${(props) => props.color};
`;

const Error = styled.span`
  font-weight: 400;
  font-size: 12px;
  line-height: 14px;
  color: var(--font-color-warn);
`;
```
코드 봤는데 지금은 className이 없어도 무방하더라구요..?

나중에 color를 border에 줄때 Props로 전달해서 처리하면 깔끔할 거 같아요...!

2023-05-13 03:30 UTC, 1yoouoo commented on src/components/Create/LinkInfo.tsx
> +`;
제가 선호하는 방식으로 바꿔봤어요

코멘트주세요!

2023-05-14 18:04 UTC, dev-hamster commented on src/components/Create/LinkInfo.tsx
> +`;
Wrapper 내부의 요소들을 스타일드 컴포넌트로 만들면 어떤 장점이 있나용?
저는 Wrapper 내부의 요소들은 클래스명으로 작업했는데
- 모듈로 사용하지 않을 예정
- 클래스명 난수화를 하지 않아도 됨
이러한 이유였습니다~~

2023-05-14 18:08 UTC, dev-hamster commented on src/components/Input/index.tsx
> +`;
넵 알겠습니다!!

2023-05-15 04:37 UTC, dev-hamster commented on src/components/Input/index.tsx
> +`;
className prop 삭제했습니다~~

2023-05-15 05:11 UTC, 1yoouoo commented on src/components/Create/LinkInfo.tsx
> +`;
말씀하신대로 재사용안하고 클래스명 난수화안해도 되는 상황에서는 수정 전 코드가 더 적합해보이긴해요

개발자 취향이라 취사선택하시면 되지만 프로젝트 모든 코드에 JSX일관성이 있으면 전체적인 코드가독성이 높아질 거 같은 생각이라
바꿔봤어요..! 제 취향이어서 적절하다고 생각되는 부분 골라서 사용하심 될 거 같아요!

2023-05-15 05:11 UTC, 1yoouoo approved these changes

2023-05-15 05:17 UTC, dev-hamster commented on src/components/Create/LinkInfo.tsx
> +`;
의견 감사합니다! 코드가독성이 중요한 컴포넌트, 페이지에서는 적용하겠습니다~~

2023-05-15 05:18 UTC, merged